### ISSUE TITLE
Change unsigned long and short to int16/int64/etc,

### ISSUE THREAD

**Issue by phoenixfury** [llohse/libnpy#39]
ament_cpplint is complaining about the C type long & short, can you please use int16/int64/etc, instead? Thanks for your awesome work!

**Comment by llohse** [comment]
Different linters complain about different coding styles - there is no way around that.
I would not consider `long` and `short` to be C style, since they are also the fundamental types in C++. In fact the fixed-width types require to include `<cstdint>`.

I have been using the fundamental types because that is what the numpy folks are doing. If there is a good argument against this, I would reconsider my decision.
